package rules;

import com.chenj.entity.Order;

// 规则1：100元一下，不加分
rule "score_1"
when
    $order: Order(amout < 100)
then 
    $order.setScore(0);
    System.out.println("成功匹配到规则1：100元一下，不加分");
end
 
 // 规则2：100元-500元 加100分
rule "score_2"
when
    $order: Order(amout > 100 && amout <= 500)
then
    $order.setScore(100);
    System.out.println("成功匹配到 规则2：100元-500元 加100分");
end

 // 规则3：500元-1000元 加500分
rule "score_3"
when  $order: Order(amout > 500 && amout <= 1000)
then
    $order.setScore(500);
    System.out.println("成功匹配到 规则3：500元-1000元 加500分");
end

 // 规则4：1000元以上 加1000分
rule "score_4"
when
    $order: Order(amout > 1000)
then
    $order.setScore(1000);
    System.out.println(" 成功匹配到 规则4：1000元以上 加1000分");
end
